name: "CI"

concurrency:
    group: "ci-${{ github.head_ref || github.run_id }}"
    cancel-in-progress: true

on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    ci:
        name: "Execute"
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "lowest"
                    - "highest"
                    - "locked"
                php-version:
                    - "8.1"
                    - "8.2"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: "Install PHP"
              uses: "shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401" # v2
              with:
                  coverage: "pcov"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1

            - name: "Install dependencies"
              uses: ramsey/composer-install@v3
              with:
                dependency-versions: "${{ matrix.dependencies }}"

            - name: "Validate Composer dependencies"
              run: "composer validate"

            - name: "Run linting (src)"
              run: "bin/parallel-lint src"

            - name: "Run linting (tests)"
              run: "bin/parallel-lint tests"

            - name: "Code style check"
              if: ${{ matrix.dependencies == 'locked' }}
              run: "bin/php-cs-fixer fix --config='./tools/php-cs-fixer/config.php' --show-progress=none --dry-run --no-interaction --diff -v --using-cache=no"

            - name: "Run PHPStan"
              if: ${{ matrix.dependencies != 'lowest' }}
              run: "bin/phpstan analyse --memory-limit=-1 src/ tests/ --ansi --no-progress"

            - name: "Run Rector"
              if: ${{ matrix.dependencies == 'locked' }}
              run: "bin/rector --dry-run --ansi --no-progress-bar"

            - name: "Run PHPUnit unit tests"
              run: "bin/phpunit --colors --testsuite=unit --do-not-cache-result"

            - name: "Run PHPUnit functional tests"
              run: "bin/phpunit --colors --testsuite=functional --do-not-cache-result"
